# Generated by Django 2.0.2 on 2018-02-08 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20180208_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioncategory',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
