# Generated by Django 2.0.2 on 2018-02-20 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20180216_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.ActionCategory'),
        ),
        migrations.AlterField(
            model_name='actioncategory',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
