# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_info', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('icon_name', models.CharField(max_length=200)),
                ('temperature', models.IntegerField(default=0)),
                ('humidity', models.IntegerField(default=0)),
                ('pressure', models.IntegerField(default=0)),
                ('temperature_min', models.IntegerField(default=0)),
                ('temperature_max', models.IntegerField(default=0)),
                ('wind_speed', models.FloatField(default=0.0)),
                ('wind_deg', models.FloatField(default=0.0)),
                ('sunrise', models.DateTimeField(default=django.utils.timezone.now)),
                ('sunset', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(default=0)),
                ('temperature_min', models.IntegerField(default=0)),
                ('temperature_max', models.IntegerField(default=0)),
                ('pressure', models.IntegerField(default=0)),
                ('humidity', models.IntegerField(default=0)),
                ('main_info', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('icon_name', models.CharField(max_length=200)),
                ('wind_speed', models.FloatField(default=0.0)),
                ('wind_deg', models.FloatField(default=0.0)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
