# Generated by Django 2.0.2 on 2018-02-23 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiotArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=400)),
                ('content', models.TextField(default='')),
                ('snippet', models.TextField(default='')),
                ('main_pic', models.CharField(default='', max_length=200)),
                ('link', models.CharField(default='', max_length=200)),
                ('author', models.CharField(default='', max_length=200)),
                ('original_ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('radiot_ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('feed', models.TextField(default='')),
                ('slug', models.TextField(default='')),
                ('comments', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
