# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_currency_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='city_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='weather',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
