# Generated by Django 2.0.2 on 2018-02-26 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_radiotarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevByEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=400)),
                ('content', models.TextField(default='')),
                ('link', models.CharField(default='', max_length=400)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
