# Generated by Django 2.0.2 on 2018-02-27 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_devbyevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiotarticle',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
