# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180126_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='visibility',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='weather',
            name='icon_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='weather',
            name='main_info',
            field=models.CharField(default='', max_length=200),
        ),
    ]
