# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20180126_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
