# Generated by Django 2.0.2 on 2018-03-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_radiotarticle_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='requested_city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='weatherforecast',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='weatherforecast',
            name='requested_city',
            field=models.CharField(default='', max_length=200),
        ),
    ]
