# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_weather_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
                ('currency_from', models.CharField(default='', max_length=200)),
                ('currency_to', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(default='', max_length=200)),
                ('rate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='currency',
            name='abbreviation',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='currency',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='currency',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
