# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20180130_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencystatistics',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
