# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_currencystatistics_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('symbol', models.CharField(default='', max_length=200)),
                ('rank', models.IntegerField(default=0)),
                ('price_usd', models.FloatField(default=0.0)),
                ('price_btc', models.FloatField(default=0.0)),
                ('change_24h', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_usd', models.IntegerField(default=0.0)),
                ('total_usd_day_volume', models.IntegerField(default=0.0)),
                ('active_markets', models.IntegerField(default=0.0)),
                ('active_currencies', models.IntegerField(default=0)),
                ('bitcoin_percent', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
