# Generated by Django 2.0.2 on 2018-04-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_expensescategory_expensesrecord_incomerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitiesrecord',
            name='gas',
            field=models.IntegerField(default=0),
        ),
    ]
